"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# 專案根目錄位置，後續會用來組合模板、靜態檔與資料庫路徑。
BASE_DIR = Path(__file__).resolve().parent.parent


# Django 專案密鑰，正式上線時不應直接寫在程式中。
SECRET_KEY = 'django-insecure-)k!ru0ef)5-@^n63_xh@sk_dwijpli+-nh=dy-64(j(5s=j-br'

# 開發模式下開啟除錯資訊，正式環境應改為 False。
DEBUG = True

# 允許哪些主機名稱存取這個 Django 專案。
ALLOWED_HOSTS = ["*"]


# 註冊專案中啟用的 app，包含 Django 內建模組、DRF 與 library。
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'library',
]

# 請求進入 Django 後，依序經過的中介層設定。
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 指定主路由設定檔位置。
ROOT_URLCONF = 'library_system.urls'

# 模板引擎設定，讓 Django 能找到 HTML 模板。
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI 入口，部署時伺服器會從這裡載入 Django 應用。
WSGI_APPLICATION = 'library_system.wsgi.application'


# 使用 SQLite 作為目前專案的資料庫。
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Django 內建的密碼驗證規則。
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 系統語系設定為繁體中文。
LANGUAGE_CODE = 'zh-hant'

# 系統時區設定為台北時區。
TIME_ZONE = 'Asia/Taipei'

# 啟用 Django 國際化功能。
USE_I18N = True

# 使用具時區概念的時間格式。
USE_TZ = True


# 前端靜態資源的 URL 前綴。
STATIC_URL = 'static/'

# 指定本地靜態檔資料夾位置。
STATICFILES_DIRS = [BASE_DIR / 'static']

# 新建立資料表時，預設使用 BigAutoField 作為主鍵型別。
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
